# Default values for api-sandbox.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: 368696334230.dkr.ecr.ap-south-1.amazonaws.com/cdr-demo-backend
  tag: 0.0.1
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations: 
    # zalando.org/skipper-filter: modPath("^/dashboard", "") -> setResponseHeader("X-Frame-Options", "SAMEORIGIN") -> setResponseHeader("Cache-Control", "no-cache, no-store, max-age=0, must-revalidate") -> setResponseHeader("Pragma", "no-cache") -> setResponseHeader("Expires", "0") -> setResponseHeader("Expires", "0")  -> setResponseHeader("X-Content-Type-Options", "nosniff") -> setResponseHeader("Strict-Transport-Security", "max-age=31536000 ; includeSubDomains") -> setResponseHeader("X-XSS-Protection", "1; mode=block")
  path: /
  hosts:
    - demo-be.services.cua.oip.virtusa.dev
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
# livenessProbe:
#   httpGet:
#     path: /
#     port: http
#   initialDelaySeconds: 120
# readinessProbe:
#   httpGet:
#     path: /
#     port: http
#   initialDelaySeconds: 120
